services:
  - docker

before_install:
  - ls
  - rm -f cmake/FindMATLAB.cmake

install:
  - docker run --rm -v `pwd`:/local -it jgillis/meco_builder:xenial-win-py36 /bin/bash "source /local/travis.sh"
